import * as fs from "fs";
import * as path from "path";
import type { AdapterContext, ApplyResult } from "./types";

const SKIP_DIRS = new Set([".git", "node_modules", "references"]);

function copySkillsRecursive(srcDir: string, destDir: string): string[] {
  const copied: string[] = [];
  if (!fs.existsSync(srcDir)) return copied;
  if (!fs.existsSync(destDir)) {
    fs.mkdirSync(destDir, { recursive: true });
  }
  const entries = fs.readdirSync(srcDir, { withFileTypes: true });
  for (const e of entries) {
    const srcPath = path.join(srcDir, e.name);
    const destPath = path.join(destDir, e.name);
    if (e.isDirectory()) {
      if (SKIP_DIRS.has(e.name)) continue;
      copied.push(...copySkillsRecursive(srcPath, destPath));
    } else {
      fs.copyFileSync(srcPath, destPath);
      copied.push(path.relative(destDir, destPath));
    }
  }
  return copied;
}

function buildAgentsMd(extensionPath: string): string {
  const rulesDir = path.join(extensionPath, ".cursor", "rules");
  const agentsDir = path.join(extensionPath, ".cursor", "agents");

  function stripFrontmatter(content: string): string {
    const match = content.match(/^---\r?\n[\s\S]*?\r?\n---\r?\n([\s\S]*)$/);
    return match ? match[1].trim() : content;
  }

  const parts: string[] = [
    "# Payoy's workflow (Plan → Code → Review/Test)",
    "",
    "Follow the compounding dev cycle and apply these rules and agent roles.",
    "",
    "## Rules",
    "",
  ];
  if (fs.existsSync(rulesDir)) {
    const entries = fs.readdirSync(rulesDir, { withFileTypes: true });
    for (const e of entries) {
      if (!e.isFile() || (!e.name.endsWith(".mdc") && !e.name.endsWith(".md"))) continue;
      if (e.name === "README.md") continue;
      const raw = fs.readFileSync(path.join(rulesDir, e.name), "utf-8");
      parts.push("### " + e.name.replace(/\.(mdc|md)$/, "").replace(/-/g, " "));
      parts.push("");
      parts.push(stripFrontmatter(raw));
      parts.push("");
    }
  }
  parts.push("## Agents (use when relevant)");
  parts.push("");
  if (fs.existsSync(agentsDir)) {
    const files = fs.readdirSync(agentsDir).filter((f: string) => f.endsWith(".md"));
    for (const f of files) {
      const raw = fs.readFileSync(path.join(agentsDir, f), "utf-8");
      const nameMatch = raw.match(/name:\s*(\S+)/);
      const descMatch = raw.match(/description:\s*(.+)/);
      const name = nameMatch ? nameMatch[1] : f.replace(".md", "");
      const desc = descMatch ? descMatch[1].trim() : "";
      parts.push(`- **${name}**: ${desc}`);
    }
  }
  parts.push("");
  parts.push("---");
  parts.push("*Generated by Payoy's Cursor Sub-Agents extension for Codex.*");
  return parts.join("\n");
}

/**
 * Apply workflow for Codex: .agents/skills (from .cursor/skills) and AGENTS.md.
 */
export async function applyCodex(context: AdapterContext): Promise<ApplyResult> {
  const { extensionPath, workspaceRootPath } = context;
  if (!workspaceRootPath) {
    return {
      success: false,
      message: "No workspace folder open. Open a folder first, then run the command again.",
    };
  }
  const skillsSrc = path.join(extensionPath, ".cursor", "skills");
  if (!fs.existsSync(skillsSrc)) {
    return {
      success: false,
      message: "Extension workflow files not found. Reinstall the extension.",
    };
  }
  const details: string[] = [];
  try {
    // Codex uses .agents/skills at repo root
    const agentsDir = path.join(workspaceRootPath, ".agents");
    const skillsDest = path.join(agentsDir, "skills");
    if (!fs.existsSync(skillsDest)) fs.mkdirSync(skillsDest, { recursive: true });
    copySkillsRecursive(skillsSrc, skillsDest);
    details.push(".agents/skills/ (from .cursor/skills)");

    const agentsMdPath = path.join(workspaceRootPath, "AGENTS.md");
    fs.writeFileSync(agentsMdPath, buildAgentsMd(extensionPath), "utf-8");
    details.push("AGENTS.md (rules + agent summaries)");

    return {
      success: true,
      message: "Codex workflow applied to this workspace.",
      details,
    };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return {
      success: false,
      message: `Failed to apply Codex workflow: ${message}`,
      details,
    };
  }
}
