import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import type { AdapterContext, ApplyResult } from "./types";
import { syncSkillsToCodexFromSource } from "../installCodexSkills";
import { buildCompoundingDevCycleContent } from "../compoundingDevCycle";

function buildAgentsMd(extensionPath: string): string {
  const rulesDir = path.join(extensionPath, ".cursor", "rules");
  const agentsDir = path.join(extensionPath, ".cursor", "agents");

  function stripFrontmatter(content: string): string {
    const match = content.match(/^---\r?\n[\s\S]*?\r?\n---\r?\n([\s\S]*)$/);
    return match ? match[1].trim() : content;
  }

  const parts: string[] = [
    "# Plan-Code-Review workflow (Plan → Code → Review/Test)",
    "",
    "Follow the compounding dev cycle and apply these rules and agent roles.",
    "",
    "## Rules",
    "",
  ];
  if (fs.existsSync(rulesDir)) {
    const entries = fs.readdirSync(rulesDir, { withFileTypes: true });
    for (const e of entries) {
      if (!e.isFile() || (!e.name.endsWith(".mdc") && !e.name.endsWith(".md"))) continue;
      if (e.name === "README.md") continue;
      const raw = fs.readFileSync(path.join(rulesDir, e.name), "utf-8");
      parts.push("### " + e.name.replace(/\.(mdc|md)$/, "").replace(/-/g, " "));
      parts.push("");
      parts.push(stripFrontmatter(raw));
      parts.push("");
    }
  }
  parts.push("## Agents (use when relevant)");
  parts.push("");
  if (fs.existsSync(agentsDir)) {
    const files = fs.readdirSync(agentsDir).filter((f: string) => f.endsWith(".md"));
    for (const f of files) {
      const raw = fs.readFileSync(path.join(agentsDir, f), "utf-8");
      const nameMatch = raw.match(/name:\s*(\S+)/);
      const descMatch = raw.match(/description:\s*(.+)/);
      const name = nameMatch ? nameMatch[1] : f.replace(".md", "");
      const desc = descMatch ? descMatch[1].trim() : "";
      parts.push(`- **${name}**: ${desc}`);
    }
  }
  parts.push("");
  parts.push("---");
  parts.push("*Generated by Plan-Code-Review Workflow extension for Codex.*");
  return parts.join("\n");
}

/**
 * Apply workflow for Codex: sync .cursor/skills to ~/.codex/skills and write AGENTS.md.
 * Does not create .agents/skills; skills are synced directly to Codex.
 */
export async function applyCodex(context: AdapterContext): Promise<ApplyResult> {
  const { extensionPath, workspaceRootPath } = context;
  if (!workspaceRootPath) {
    return {
      success: false,
      message: "No workspace folder open. Open a folder first, then run the command again.",
    };
  }
  const skillsSrc = path.join(extensionPath, ".cursor", "skills");
  if (!fs.existsSync(skillsSrc)) {
    return {
      success: false,
      message: "Extension workflow files not found. Reinstall the extension.",
    };
  }
  const details: string[] = [];
  try {
    const syncResult = syncSkillsToCodexFromSource(skillsSrc);
    if (!syncResult.success) {
      return {
        success: false,
        message: syncResult.message,
        details: syncResult.details,
      };
    }
    details.push("~/.codex/skills/ (synced from .cursor/skills)");
    if (syncResult.details?.length) {
      details.push(...syncResult.details.slice(1));
    }

    // User-level AGENTS.md: impose compounding dev cycle for all projects (Codex merges global + project)
    const codexUserDir = path.join(os.homedir(), ".codex");
    if (!fs.existsSync(codexUserDir)) fs.mkdirSync(codexUserDir, { recursive: true });
    const userAgentsPath = path.join(codexUserDir, "AGENTS.md");
    const userAgentsContent = [
      "# Plan-Code-Review workflow (user-level)",
      "",
      "Apply the compounding dev cycle in every project. Project-level AGENTS.md adds rules and agents for this repo.",
      "",
      "---",
      "",
      buildCompoundingDevCycleContent(extensionPath),
      "",
      "---",
      "*User-level rules from Plan-Code-Review Workflow extension.*",
    ].join("\n");
    fs.writeFileSync(userAgentsPath, userAgentsContent, "utf-8");
    details.push("~/.codex/AGENTS.md (compounding dev cycle at user level)");

    const agentsMdPath = path.join(workspaceRootPath, "AGENTS.md");
    fs.writeFileSync(agentsMdPath, buildAgentsMd(extensionPath), "utf-8");
    details.push("AGENTS.md in workspace (rules + agent summaries)");

    return {
      success: true,
      message:
        "Codex workflow applied: user-level compounding dev cycle + workspace AGENTS.md.",
      details,
    };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return {
      success: false,
      message: `Failed to apply Codex workflow: ${message}`,
      details,
    };
  }
}
