import * as fs from "fs";
import * as path from "path";
import type { AdapterContext, ApplyResult } from "./types";

function stripFrontmatter(content: string): string {
  const match = content.match(/^---\r?\n[\s\S]*?\r?\n---\r?\n([\s\S]*)$/);
  return match ? match[1].trim() : content;
}

function buildInstructionsMd(extensionPath: string): string {
  const rulesDir = path.join(extensionPath, ".cursor", "rules");
  const agentsDir = path.join(extensionPath, ".cursor", "agents");
  const parts: string[] = [
    "# Payoy's workflow (Plan → Code → Review/Test)",
    "",
    "Apply these rules and use the referenced agent perspectives when working in this repo.",
    "",
    "## Rules",
    "",
  ];
  if (fs.existsSync(rulesDir)) {
    const entries = fs.readdirSync(rulesDir, { withFileTypes: true });
    for (const e of entries) {
      if (!e.isFile() || (!e.name.endsWith(".mdc") && !e.name.endsWith(".md"))) continue;
      if (e.name === "README.md") continue;
      const raw = fs.readFileSync(path.join(rulesDir, e.name), "utf-8");
      parts.push("### " + e.name.replace(/\.(mdc|md)$/, "").replace(/-/g, " "));
      parts.push("");
      parts.push(stripFrontmatter(raw));
      parts.push("");
    }
  }
  parts.push("## Agent roles (apply when relevant)");
  parts.push("");
  if (fs.existsSync(agentsDir)) {
    const files = fs.readdirSync(agentsDir).filter((f: string) => f.endsWith(".md"));
    for (const f of files) {
      const raw = fs.readFileSync(path.join(agentsDir, f), "utf-8");
      const nameMatch = raw.match(/name:\s*(\S+)/);
      const descMatch = raw.match(/description:\s*(.+)/);
      const name = nameMatch ? nameMatch[1] : f.replace(".md", "");
      const desc = descMatch ? descMatch[1].trim() : "";
      parts.push(`- **${name}**: ${desc}`);
    }
  }
  parts.push("");
  parts.push("---");
  parts.push("*Generated by Payoy's Cursor Sub-Agents extension for GitHub Copilot.*");
  return parts.join("\n");
}

/**
 * Apply workflow for GitHub Copilot: .github/copilot-instructions.md and/or AGENTS.md.
 */
export async function applyCopilot(context: AdapterContext): Promise<ApplyResult> {
  const { extensionPath, workspaceRootPath } = context;
  if (!workspaceRootPath) {
    return {
      success: false,
      message: "No workspace folder open. Open a folder first, then run the command again.",
    };
  }
  const details: string[] = [];
  try {
    const content = buildInstructionsMd(extensionPath);

    // .github/copilot-instructions.md (project-wide)
    const githubDir = path.join(workspaceRootPath, ".github");
    if (!fs.existsSync(githubDir)) fs.mkdirSync(githubDir, { recursive: true });
    const copilotPath = path.join(githubDir, "copilot-instructions.md");
    fs.writeFileSync(copilotPath, content, "utf-8");
    details.push(".github/copilot-instructions.md");

    // AGENTS.md at root (Copilot and Codex both use it)
    const agentsPath = path.join(workspaceRootPath, "AGENTS.md");
    fs.writeFileSync(agentsPath, content, "utf-8");
    details.push("AGENTS.md (agent instructions at repo root)");

    return {
      success: true,
      message: "GitHub Copilot workflow applied to this workspace.",
      details,
    };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return {
      success: false,
      message: `Failed to apply Copilot workflow: ${message}`,
      details,
    };
  }
}
