import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import type { AdapterContext, ApplyResult, RemoveResult } from "./types";
import {
  getWorkspaceManifest,
  getUserManifest,
  recordWorkspaceApplied,
  recordUserApplied,
  clearWorkspaceManifest,
  clearUserManifest,
} from "../workflowManifest";

const INSTRUCTIONS_FILE_NAME = "plan-code-review-workflow.instructions.md";

function stripFrontmatter(content: string): string {
  const match = content.match(/^---\r?\n[\s\S]*?\r?\n---\r?\n([\s\S]*)$/);
  return match ? match[1].trim() : content;
}

function buildInstructionsMd(extensionPath: string): string {
  const rulesDir = path.join(extensionPath, ".cursor", "rules");
  const agentsDir = path.join(extensionPath, ".cursor", "agents");
  const parts: string[] = [
    "# Plan-Code-Review workflow (Plan → Code → Review/Test)",
    "",
    "Apply these rules and use the referenced agent perspectives when working in this repo.",
    "",
    "## Rules",
    "",
  ];
  if (fs.existsSync(rulesDir)) {
    const entries = fs.readdirSync(rulesDir, { withFileTypes: true });
    for (const e of entries) {
      if (!e.isFile() || (!e.name.endsWith(".mdc") && !e.name.endsWith(".md"))) continue;
      if (e.name === "README.md") continue;
      const raw = fs.readFileSync(path.join(rulesDir, e.name), "utf-8");
      parts.push("### " + e.name.replace(/\.(mdc|md)$/, "").replace(/-/g, " "));
      parts.push("");
      parts.push(stripFrontmatter(raw));
      parts.push("");
    }
  }
  parts.push("## Agent roles (apply when relevant)");
  parts.push("");
  if (fs.existsSync(agentsDir)) {
    const files = fs.readdirSync(agentsDir).filter((f: string) => f.endsWith(".md"));
    for (const f of files) {
      const raw = fs.readFileSync(path.join(agentsDir, f), "utf-8");
      const nameMatch = raw.match(/name:\s*(\S+)/);
      const descMatch = raw.match(/description:\s*(.+)/);
      const name = nameMatch ? nameMatch[1] : f.replace(".md", "");
      const desc = descMatch ? descMatch[1].trim() : "";
      parts.push(`- **${name}**: ${desc}`);
    }
  }
  parts.push("");
  parts.push("---");
  parts.push("*Generated by Plan-Code-Review Workflow extension for GitHub Copilot.*");
  return parts.join("\n");
}

/** Build skills section from .cursor/skills (name + description from each SKILL.md). */
function buildSkillsSection(extensionPath: string): string {
  const skillsDir = path.join(extensionPath, ".cursor", "skills");
  const parts: string[] = ["## Skills (use when relevant)", ""];
  if (!fs.existsSync(skillsDir)) return parts.join("\n");
  const entries = fs.readdirSync(skillsDir, { withFileTypes: true });
  for (const e of entries) {
    if (!e.isDirectory()) continue;
    const skillMdPath = path.join(skillsDir, e.name, "SKILL.md");
    if (!fs.existsSync(skillMdPath)) continue;
    const raw = fs.readFileSync(skillMdPath, "utf-8");
    const nameMatch = raw.match(/name:\s*(\S+)/);
    const descMatch = raw.match(/description:\s*(.+)/);
    const name = nameMatch ? nameMatch[1] : e.name;
    const desc = descMatch ? descMatch[1].trim() : "";
    parts.push(`- **${name}**: ${desc}`);
  }
  parts.push("");
  return parts.join("\n");
}

/** Full user-level instructions: rules + agents + skills (for Copilot prompts folder). */
function buildUserLevelInstructionsMd(extensionPath: string): string {
  const rules = buildInstructionsMd(extensionPath);
  const skillsSection = buildSkillsSection(extensionPath);
  return [rules.trimEnd(), "", "---", "", skillsSection.trimEnd(), ""].join("\n");
}

/** User-level prompts directories for GitHub Copilot / VS Code (Code and Cursor). */
function getUserPromptsDirs(): string[] {
  const home = os.homedir();
  const dirs: string[] = [];
  if (process.platform === "darwin") {
    dirs.push(path.join(home, "Library", "Application Support", "Code", "User", "prompts"));
    dirs.push(path.join(home, "Library", "Application Support", "Cursor", "User", "prompts"));
  } else if (process.platform === "win32") {
    const appData = process.env.APPDATA || path.join(home, "AppData", "Roaming");
    dirs.push(path.join(appData, "Code", "User", "prompts"));
    dirs.push(path.join(appData, "Cursor", "User", "prompts"));
  } else {
    dirs.push(path.join(home, ".config", "Code", "User", "prompts"));
    dirs.push(path.join(home, ".config", "Cursor", "User", "prompts"));
  }
  return dirs;
}

/**
 * Apply workflow for GitHub Copilot: user-level rules + agents + skills (prompts folder) and workspace .github/copilot-instructions.md + AGENTS.md.
 */
export async function applyCopilot(context: AdapterContext): Promise<ApplyResult> {
  const { extensionPath, workspaceRootPath } = context;
  if (!workspaceRootPath) {
    return {
      success: false,
      message: "No workspace folder open. Open a folder first, then run the command again.",
    };
  }
  const details: string[] = [];
  try {
    // User-level: full workflow (rules + agents + skills) so it applies to all chats in all workspaces
    const userLevelContent = buildUserLevelInstructionsMd(extensionPath);
    const instructionsContent = [
      "---",
      "name: 'Plan-Code-Review Workflow (rules, agents, skills)'",
      "description: 'Plan → Code → Review/Test cycle, rules, agent roles, and skills'",
      'applyTo: "**"',
      "---",
      "",
      userLevelContent,
    ].join("\n");
    const instructionsFileName = INSTRUCTIONS_FILE_NAME;
    let userLevelWritten = 0;
    const writtenPromptPaths: string[] = [];
    for (const promptsDir of getUserPromptsDirs()) {
      try {
        if (!fs.existsSync(promptsDir)) fs.mkdirSync(promptsDir, { recursive: true });
        const filePath = path.join(promptsDir, instructionsFileName);
        fs.writeFileSync(filePath, instructionsContent, "utf-8");
        writtenPromptPaths.push(filePath);
        userLevelWritten++;
      } catch {
        // Skip if we can't write (e.g. dir not used by this IDE)
      }
    }
    if (userLevelWritten > 0) {
      recordUserApplied({
        copilot: { promptPaths: writtenPromptPaths, appliedAt: new Date().toISOString() },
      });
    }
    if (userLevelWritten > 0) {
      details.push(
        `User-level: rules, agents, skills in prompts folder (${userLevelWritten} location(s))`
      );
    }

    const content = buildInstructionsMd(extensionPath);

    // .github/copilot-instructions.md (project-wide)
    const githubDir = path.join(workspaceRootPath, ".github");
    if (!fs.existsSync(githubDir)) fs.mkdirSync(githubDir, { recursive: true });
    const copilotPath = path.join(githubDir, "copilot-instructions.md");
    fs.writeFileSync(copilotPath, content, "utf-8");
    details.push(".github/copilot-instructions.md");

    // AGENTS.md at root (Copilot and Codex both use it)
    const agentsPath = path.join(workspaceRootPath, "AGENTS.md");
    fs.writeFileSync(agentsPath, content, "utf-8");
    details.push("AGENTS.md (agent instructions at repo root)");

    const copilotFiles = [".github/copilot-instructions.md", "AGENTS.md"];
    recordWorkspaceApplied(workspaceRootPath, {
      copilot: { files: copilotFiles, appliedAt: new Date().toISOString() },
    });

    return {
      success: true,
      message:
        "GitHub Copilot workflow applied: user-level rules, agents, skills + workspace instructions.",
      details,
    };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return {
      success: false,
      message: `Failed to apply Copilot workflow: ${message}`,
      details,
    };
  }
}

/**
 * Remove GitHub Copilot workflow only from paths recorded in the manifest (extension-added only).
 */
export async function removeCopilot(context: AdapterContext): Promise<RemoveResult> {
  const { workspaceRootPath } = context;
  const details: string[] = [];
  const errors: string[] = [];
  const workspaceManifest = getWorkspaceManifest(workspaceRootPath);
  const userManifest = getUserManifest();

  // Remove only user prompt files we recorded
  if (userManifest?.copilot?.promptPaths?.length) {
    for (const filePath of userManifest.copilot.promptPaths) {
      if (fs.existsSync(filePath)) {
        try {
          fs.unlinkSync(filePath);
          details.push(`Removed ${filePath}`);
        } catch (err) {
          const message = err instanceof Error ? err.message : String(err);
          errors.push(`${filePath}: ${message}`);
        }
      }
    }
    clearUserManifest(["copilot"]);
  }

  // Remove only workspace files we recorded
  if (workspaceRootPath && workspaceManifest?.copilot?.files?.length) {
    for (const rel of workspaceManifest.copilot.files) {
      const filePath = path.join(workspaceRootPath, rel);
      if (fs.existsSync(filePath)) {
        try {
          fs.unlinkSync(filePath);
          details.push(`Removed ${filePath}`);
        } catch (err) {
          const message = err instanceof Error ? err.message : String(err);
          errors.push(`${filePath}: ${message}`);
        }
      }
    }
    clearWorkspaceManifest(workspaceRootPath, ["copilot"]);
  }

  if (errors.length > 0) {
    return {
      success: false,
      message: "Failed to remove some Copilot workflow files: " + errors.join("; "),
      details,
    };
  }
  const removed = details.length > 0;
  return {
    success: true,
    message: removed
      ? "GitHub Copilot workflow removed from recorded paths only."
      : "No Copilot workflow applied by this extension (nothing to remove).",
    details: details.length > 0 ? details : undefined,
  };
}
